import { useEffect, useState } from "react";
import { deleteAdminPlace360BusinessMetrics, deleteAdminPlace360Snapshot, getAdminPlace360BusinessMetrics, getAdminPlace360DetailUsage, getAdminPlace360Progress, getAdminPlace360Ranks, getAdminPlace360Snapshots, Place360BusinessAdminRow, Place360DetailUsage, Place360ProgressAdminRow, Place360RankAdminRow, Place360Snapshot, resetAdminPlace360DetailUsage, resetAdminPlace360Progress } from "../lib/supabase";

type Props = { showToast?: (message: string, type?: any) => void };

export default function Place360AdminManager({ showToast }: Props) {
  const [rows, setRows] = useState<Place360Snapshot[]>([]);
  const [search, setSearch] = useState("");
  const [loading, setLoading] = useState(false);
  const [usage, setUsage] = useState<Place360DetailUsage[]>([]);
  const [businessRows, setBusinessRows] = useState<Place360BusinessAdminRow[]>([]);
  const [progressRows, setProgressRows] = useState<Place360ProgressAdminRow[]>([]);
  const [rankRows, setRankRows] = useState<Place360RankAdminRow[]>([]);

  const load = async (query = search) => {
    setLoading(true);
    try { const [nextRows, nextUsage, nextBusinessRows, nextProgressRows, nextRankRows] = await Promise.all([getAdminPlace360Snapshots(query.trim()), getAdminPlace360DetailUsage(), getAdminPlace360BusinessMetrics(), getAdminPlace360Progress(), getAdminPlace360Ranks(query.trim())]); const normalized = query.trim().toLocaleLowerCase("ko-KR"); setRows(nextRows); setUsage(nextUsage); setRankRows(nextRankRows); setBusinessRows(nextBusinessRows.filter(row => !normalized || [row.store_name, row.member_name, row.email].some(value => value.toLocaleLowerCase("ko-KR").includes(normalized)))); setProgressRows(nextProgressRows.filter(row => !normalized || [row.store_name, row.member_name, row.email].some(value => (value || "").toLocaleLowerCase("ko-KR").includes(normalized)))); }
    catch (error: any) { showToast?.(error?.message || "플레이스 365 기록을 불러오지 못했어요", "error"); }
    finally { setLoading(false); }
  };

  useEffect(() => { void load(""); }, []); // 관리자 화면 진입 시 한 번만 최신 기록 조회

  const remove = async (row: Place360Snapshot) => {
    if (!window.confirm(`${row.store_name}의 ${row.measured_on} 측정 기록을 삭제할까요?`)) return;
    try { await deleteAdminPlace360Snapshot(row.id); setRows(list => list.filter(item => item.id !== row.id)); showToast?.("측정 기록을 삭제했어요", "success"); }
    catch (error: any) { showToast?.(error?.message || "삭제하지 못했어요", "error"); }
  };
  const resetUsage = async (row: Place360DetailUsage) => {
    if (!window.confirm(`${row.member_name || row.email} 회원의 오늘 고객 화면 확인 사용량을 0회로 초기화할까요?`)) return;
    try { await resetAdminPlace360DetailUsage(row.user_id); setUsage(list => list.map(item => item.user_id === row.user_id ? { ...item, used: 0 } : item)); showToast?.("오늘 사용량을 초기화했어요", "success"); }
    catch (error: any) { showToast?.(error?.message || "사용량을 초기화하지 못했어요", "error"); }
  };
  const removeBusinessMetrics = async (row: Place360BusinessAdminRow) => {
    if (!window.confirm(`${row.store_name}의 신규·재방문·광고 운영자료를 삭제할까요?`)) return;
    try { await deleteAdminPlace360BusinessMetrics(row.id); setBusinessRows(list => list.filter(item => item.id !== row.id)); showToast?.("운영자료를 삭제했어요", "success"); }
    catch (error: any) { showToast?.(error?.message || "운영자료를 삭제하지 못했어요", "error"); }
  };
  const resetProgress = async (row: Place360ProgressAdminRow) => {
    if (!window.confirm(`${row.store_name || row.store_key}의 성장 진행 체크와 리뷰어 전달 기록을 초기화할까요?`)) return;
    try { await resetAdminPlace360Progress(row.user_id, row.store_key); setProgressRows(list => list.filter(item => !(item.user_id === row.user_id && item.store_key === row.store_key))); showToast?.("성장 진행 기록을 초기화했어요", "success"); }
    catch (error: any) { showToast?.(error?.message || "성장 진행 기록을 초기화하지 못했어요", "error"); }
  };

  return <section style={{ marginTop: 18, paddingTop: 18, borderTop: "1px solid var(--border)" }}>
    <div style={{ display: "flex", gap: 9, alignItems: "center", flexWrap: "wrap" }}><b style={{ fontSize: 16 }}>🏪 회원 매장 진단 기록 관리</b><span style={{ padding: "4px 9px", borderRadius: 99, background: "rgba(240,65,122,.1)", color: "var(--accent-text)", fontSize: 10.5, fontWeight: 900 }}>관리자 전용</span></div>
    <p style={{ margin: "6px 0 12px", color: "var(--text2)", fontSize: 12, lineHeight: 1.65 }}>회원이 측정한 매장·날짜·리뷰 비교 기록을 확인해요. 개인정보 보호를 위해 진단 수치만 관리하며 네이버 비밀번호는 저장하지 않아요.</p>
    {/* 📊 전체 현황 요약 — 관리자가 플레이스 365 사용 규모를 한눈에 */}
    {(() => {
      const stores = new Set(rows.map(r => `${r.store_key}`)).size;
      const activeMembers = new Set(businessRows.map(r => r.email)).size;
      const handoffTotal = progressRows.reduce((s, r) => s + (r.reviewer_handoff_count || 0), 0);
      const cards: [string, string | number, string][] = [
        ["측정 기록", rows.length, "🩺"],
        ["진단 매장", stores, "🏪"],
        ["운영자료 회원", activeMembers, "📊"],
        ["리뷰어 전달", handoffTotal, "🕵️"],
      ];
      return <div style={{ display: "grid", gridTemplateColumns: "repeat(4,1fr)", gap: 8, margin: "0 0 14px" }}>{cards.map(([l, v, i]) => <div key={l} style={{ padding: "11px 12px", borderRadius: 12, background: "var(--bg)", border: "1px solid var(--border)", textAlign: "center" }}><div style={{ fontSize: 18 }}>{i}</div><b style={{ display: "block", fontSize: 18, color: "var(--accent-text)", margin: "2px 0" }}>{typeof v === "number" ? v.toLocaleString() : v}</b><small style={{ color: "var(--text3)", fontSize: 10.5 }}>{l}</small></div>)}</div>;
    })()}
    <div style={{ display: "grid", gridTemplateColumns: "minmax(0,1fr) auto", gap: 8 }}><input className="inp" value={search} onChange={e => setSearch(e.target.value)} onKeyDown={e => { if (e.key === "Enter") void load(); }} placeholder="회원 이름·이메일·매장 이름 검색"/><button className="btn btn-primary" onClick={() => void load()} disabled={loading}>{loading ? "불러오는 중…" : "기록 검색"}</button></div>
    <div style={{ marginTop: 12, overflowX: "auto", WebkitOverflowScrolling: "touch" }}><div style={{ minWidth: 720, border: "1px solid var(--border)", borderRadius: 12, overflow: "hidden" }}>
      <div style={{ display: "grid", gridTemplateColumns: "1.5fr .8fr .8fr 1.2fr 70px", padding: "9px 11px", background: "var(--bg)", color: "var(--text3)", fontSize: 10.5, fontWeight: 900 }}><span>매장</span><span>방문자 리뷰</span><span>블로그 리뷰</span><span>측정일·주변 업체</span><span>관리</span></div>
      {rows.length === 0 ? <div style={{ padding: 24, textAlign: "center", color: "var(--text3)", fontSize: 12 }}>{loading ? "기록을 불러오고 있어요…" : "저장된 진단 기록이 없습니다."}</div> : rows.map(row => <div key={row.id} style={{ display: "grid", gridTemplateColumns: "1.5fr .8fr .8fr 1.2fr 70px", alignItems: "center", padding: "10px 11px", borderTop: "1px solid var(--border)", fontSize: 12 }}><span><b style={{ display: "block" }}>{row.store_name}</b><small style={{ color: "var(--text3)" }}>{[row.region, row.category].filter(Boolean).join(" · ") || "정보 없음"}</small></span><span>{row.visitor_reviews.toLocaleString()}개<br/><small style={{ color: "var(--text3)" }}>주변 {row.competitor_avg_visitor.toLocaleString()}</small></span><span>{row.blog_reviews.toLocaleString()}개<br/><small style={{ color: "var(--text3)" }}>주변 {row.competitor_avg_blog.toLocaleString()}</small></span><span>{row.measured_on}<br/><small style={{ color: "var(--text3)" }}>{row.competitor_count}곳 비교</small></span><button type="button" onClick={() => void remove(row)} style={{ minHeight: 38, border: "1px solid rgba(207,34,46,.3)", borderRadius: 9, background: "rgba(207,34,46,.08)", color: "var(--danger)", fontFamily: "inherit", fontWeight: 800, cursor: "pointer" }}>삭제</button></div>)}
    </div></div>
    <div style={{ marginTop: 18 }}><b style={{ fontSize: 14 }}>📊 회원 운영자료 진단 관리</b><p style={{ margin: "5px 0 10px", color: "var(--text3)", fontSize: 11.5 }}>회원이 직접 입력한 최근 30일 신규·재방문·광고 자료예요. 네이버 계정이나 비밀번호는 저장하지 않아요.</p><div style={{ overflowX: "auto", WebkitOverflowScrolling: "touch" }}><div style={{ minWidth: 820, border: "1px solid var(--border)", borderRadius: 12, overflow: "hidden" }}><div style={{ display: "grid", gridTemplateColumns: "1.3fr 1.2fr 1fr 1fr 1fr 80px", padding: "9px 11px", background: "var(--bg)", color: "var(--text3)", fontSize: 10.5, fontWeight: 900 }}><span>회원</span><span>매장</span><span>신규 / 재방문</span><span>광고비 / 행동</span><span>매출·저장일</span><span>관리</span></div>{businessRows.length === 0 ? <div style={{ padding: 22, textAlign: "center", color: "var(--text3)", fontSize: 12 }}>저장된 운영자료가 없습니다.</div> : businessRows.map(row => <div key={row.id} style={{ display: "grid", gridTemplateColumns: "1.3fr 1.2fr 1fr 1fr 1fr 80px", alignItems: "center", padding: "10px 11px", borderTop: "1px solid var(--border)", fontSize: 11.5 }}><span><b style={{ display: "block" }}>{row.member_name || "이름 없음"}</b><small style={{ color: "var(--text3)" }}>{row.email} · {row.plan}</small></span><span><b style={{ display: "block" }}>{row.store_name}</b><small style={{ color: "var(--text3)" }}>{row.store_key}</small></span><span>{row.current_new_customers.toLocaleString()}명 / {row.current_repeat_customers.toLocaleString()}명<br/><small style={{ color: "var(--text3)" }}>이전 {row.previous_new_customers.toLocaleString()} / {row.previous_repeat_customers.toLocaleString()}</small></span><span>{row.current_ad_spend.toLocaleString()}원 / {row.current_ad_actions.toLocaleString()}건<br/><small style={{ color: "var(--text3)" }}>이전 {row.previous_ad_spend.toLocaleString()}원 / {row.previous_ad_actions.toLocaleString()}건</small></span><span>{row.current_sales.toLocaleString()}원<br/><small style={{ color: "var(--text3)" }}>{row.measured_on}</small></span><button type="button" onClick={() => void removeBusinessMetrics(row)} style={{ minHeight: 38, border: "1px solid rgba(207,34,46,.3)", borderRadius: 9, background: "rgba(207,34,46,.08)", color: "var(--danger)", fontFamily: "inherit", fontWeight: 800, cursor: "pointer" }}>삭제</button></div>)}</div></div></div>
    <div style={{ marginTop: 18 }}><b style={{ fontSize: 14 }}>👀 오늘 고객 화면 확인 사용량</b><p style={{ margin: "5px 0 10px", color: "var(--text3)", fontSize: 11.5 }}>회원별 사용량을 확인하고, 고객 지원이 필요한 경우에만 0회로 초기화할 수 있어요.</p><div style={{ overflowX: "auto", WebkitOverflowScrolling: "touch" }}><div style={{ minWidth: 610, border: "1px solid var(--border)", borderRadius: 12, overflow: "hidden" }}><div style={{ display: "grid", gridTemplateColumns: "1.4fr .8fr .8fr 90px", padding: "9px 11px", background: "var(--bg)", color: "var(--text3)", fontSize: 10.5, fontWeight: 900 }}><span>회원</span><span>등급</span><span>오늘 사용</span><span>관리</span></div>{usage.map(row => <div key={row.user_id} style={{ display: "grid", gridTemplateColumns: "1.4fr .8fr .8fr 90px", alignItems: "center", padding: "10px 11px", borderTop: "1px solid var(--border)", fontSize: 11.5 }}><span><b style={{ display: "block" }}>{row.member_name || "이름 없음"}</b><small style={{ color: "var(--text3)" }}>{row.email}</small></span><span>{row.plan}</span><b>{row.daily_limit >= 999999 ? "무제한" : `${row.used}/${row.daily_limit}회`}</b><button type="button" disabled={row.used === 0 || row.daily_limit >= 999999} onClick={() => void resetUsage(row)} className="btn btn-secondary btn-sm">초기화</button></div>)}</div></div></div>
    <div style={{ marginTop: 18 }}><b style={{ fontSize: 14 }}>🧭 회원 성장 진행판 관리</b><p style={{ margin: "5px 0 10px", color: "var(--text3)", fontSize: 11.5 }}>매장별 오늘 미션과 리뷰어 협업 제안 전달을 확인해요. 지원이 필요할 때만 진행 기록을 초기화하세요.</p><div style={{ overflowX: "auto", WebkitOverflowScrolling: "touch" }}><div style={{ minWidth: 720, border: "1px solid var(--border)", borderRadius: 12, overflow: "hidden" }}><div style={{ display: "grid", gridTemplateColumns: "1.3fr 1.2fr .8fr .9fr 90px", padding: "9px 11px", background: "var(--bg)", color: "var(--text3)", fontSize: 10.5, fontWeight: 900 }}><span>회원</span><span>매장</span><span>미션 완료</span><span>리뷰어 전달</span><span>관리</span></div>{progressRows.length === 0 ? <div style={{ padding: 22, textAlign: "center", color: "var(--text3)", fontSize: 12 }}>저장된 성장 진행 기록이 없습니다.</div> : progressRows.map(row => <div key={`${row.user_id}:${row.store_key}`} style={{ display: "grid", gridTemplateColumns: "1.3fr 1.2fr .8fr .9fr 90px", alignItems: "center", padding: "10px 11px", borderTop: "1px solid var(--border)", fontSize: 11.5 }}><span><b style={{ display: "block" }}>{row.member_name || "이름 없음"}</b><small style={{ color: "var(--text3)" }}>{row.email} · {row.plan}</small></span><span><b>{row.store_name || "매장 이름 없음"}</b><small style={{ display: "block", color: "var(--text3)" }}>{row.store_key}</small></span><b>{(row.completed_missions || []).length}개</b><span><b>{row.reviewer_handoff_count.toLocaleString()}명</b><small style={{ display: "block", color: "var(--text3)" }}>{row.reviewer_handoff_at ? new Date(row.reviewer_handoff_at).toLocaleDateString("ko-KR") : "전달 전"}</small></span><button type="button" onClick={() => void resetProgress(row)} className="btn btn-secondary btn-sm">초기화</button></div>)}</div></div></div>
    <div style={{ marginTop: 18 }}><b style={{ fontSize: 14 }}>📈 회원 순위 측정 이력</b><p style={{ margin: "5px 0 10px", color: "var(--text3)", fontSize: 11.5 }}>회원이 키워드별로 잰 순위 기록이에요(최근 500건). 어떤 검색어에서 몇 위였는지 확인할 수 있어요.</p><div style={{ overflowX: "auto", WebkitOverflowScrolling: "touch" }}><div style={{ minWidth: 720, border: "1px solid var(--border)", borderRadius: 12, overflow: "hidden" }}><div style={{ display: "grid", gridTemplateColumns: "1.3fr 1.4fr .7fr .8fr 1fr", padding: "9px 11px", background: "var(--bg)", color: "var(--text3)", fontSize: 10.5, fontWeight: 900 }}><span>회원</span><span>키워드</span><span>순위</span><span>확인 범위</span><span>측정일시</span></div>{rankRows.length === 0 ? <div style={{ padding: 22, textAlign: "center", color: "var(--text3)", fontSize: 12 }}>저장된 순위 기록이 없습니다. (RPC 미배포 시 SQL 실행 필요)</div> : rankRows.slice(0, 200).map(row => <div key={row.id} style={{ display: "grid", gridTemplateColumns: "1.3fr 1.4fr .7fr .8fr 1fr", alignItems: "center", padding: "10px 11px", borderTop: "1px solid var(--border)", fontSize: 11.5 }}><span><b style={{ display: "block", overflow: "hidden", textOverflow: "ellipsis", whiteSpace: "nowrap" }}>{row.member_name || "이름 없음"}</b><small style={{ color: "var(--text3)" }}>{row.email}</small></span><span style={{ overflow: "hidden", textOverflow: "ellipsis", whiteSpace: "nowrap" }}><b>{row.keyword}</b><small style={{ display: "block", color: "var(--text3)" }}>{row.store_key}</small></span><b style={{ color: row.rank ? "var(--text)" : "#e0952f" }}>{row.rank ? `${row.rank}위` : "상위밖"}</b><span>상위 {row.checked_count}곳</span><small style={{ color: "var(--text3)" }}>{new Date(row.measured_at).toLocaleString("ko-KR", { month: "numeric", day: "numeric", hour: "2-digit", minute: "2-digit" })}</small></div>)}</div></div></div>
  </section>;
}
